WITH RECURSIVE seq(n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM seq WHERE n < 100000
)
INSERT INTO MEMBER (MEMBER_ID, USERNAME, AGE)
SELECT NEXT VALUE FOR MEMBER_SEQ,
    CHAR(65 + FLOOR(RAND()*26)) || CHAR(65 + FLOOR(RAND()*26)) AS USERNAME,
    20 + MOD(n, 41) AS AGE
FROM seq;